"""create customer table

Revision ID: 0005_create_customer_table
Revises: 6db39c802cda_create_service_tables
Create Date: 2026-09-22 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005_create_customer_table'
down_revision = '6db39c802cda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('primary_staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_index(op.f('ix_customers_shop_id'), 'customers', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    # Create a partial unique constraint on shop_id and mobile for non-archived customers
    # This allows reusing mobile numbers after a customer is archived
    op.execute(
        "CREATE UNIQUE INDEX uq_customers_shop_id_mobile_active ON customers (shop_id, mobile) WHERE status != 'archived'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_customers_shop_id_mobile_active")
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_shop_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###