"""Create customer_accounts table for customer portal authentication

Revision ID: 4b5174192b0d
Revises: 0009_create_receipts_communication_tables
Create Date: 2026-09-26 09:04:34.664783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b5174192b0d'
down_revision: Union[str, None] = '0009_create_receipts_communication_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_customer_accounts_customer_id'), 'customer_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_accounts_email'), 'customer_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_customer_accounts_shop_id'), 'customer_accounts', ['shop_id'], unique=False)
    op.create_index(op.f('ix_customer_accounts_status'), 'customer_accounts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_accounts_status'), table_name='customer_accounts')
    op.drop_index(op.f('ix_customer_accounts_shop_id'), table_name='customer_accounts')
    op.drop_index(op.f('ix_customer_accounts_email'), table_name='customer_accounts')
    op.drop_index(op.f('ix_customer_accounts_customer_id'), table_name='customer_accounts')
    op.drop_table('customer_accounts')
    # ### end Alembic commands ###